import XCTest
@testable import Aria___Music_Browser

/// Pins the client's doc composition (`LibraryDoc`) to the SERVER's
/// (`backend/library_index.py`). Every expected `doc_text`/`doc_hash` below
/// was generated by running the real Python `compose_doc` + `doc_hash` on the
/// same fields (script: scratchpad `gen_fixtures.py`, run against the merged
/// Slice-1 backend). If one of these fails after a backend change, the delta
/// sync contract is broken — fix the composition mismatch, do NOT re-record
/// blindly.
final class LibraryDocCompositionTests: XCTestCase {

    private func compose(
        title: String?, artist: String?, album: String?, genre: String?,
        duration: Double?, playlists: [String], affinity: [String]
    ) -> (text: String, hash: String) {
        let text = LibraryDoc.compose(
            title: title, artist: artist, album: album, genre: genre,
            durationSeconds: duration, playlists: playlists, affinity: affinity)
        return (text, LibraryDoc.hash(text))
    }

    // MARK: - Pinned server fixtures

    func test_plainTrack_matchesServerComposition() {
        let (text, hash) = compose(
            title: "Karma Police", artist: "Radiohead", album: "OK Computer",
            genre: "alternative rock", duration: 261,
            playlists: ["Road Trip", "Mellow"], affinity: ["favorite", "recent"])
        XCTAssertEqual(text, "title: karma police\nartist: radiohead\nalbum: ok computer\ngenre: alternative rock\nduration: medium\nplaylists: road trip mellow\naffinity: favorite recent")
        XCTAssertEqual(hash, "4afd1bb4f67431e6143da613c46c17b0c5037372504da4a88bdd77c052c24a91")
    }

    func test_missingFields_matchServerDefaults() {
        // nil album -> "", nil genre -> "unknown", nil duration -> "medium",
        // empty lists -> empty-after-colon lines (note the trailing spaces).
        let (text, hash) = compose(
            title: "Untitled", artist: "Unknown Artist", album: nil,
            genre: nil, duration: nil, playlists: [], affinity: [])
        XCTAssertEqual(text, "title: untitled\nartist: unknown artist\nalbum: \ngenre: unknown\nduration: medium\nplaylists: \naffinity: ")
        XCTAssertEqual(hash, "513ca95de1ec388fefdf0d84307f7ad6aab8f42f822925a11c9ecb4344162320")
    }

    func test_whitespaceCollapse_case_unicode_matchServer() {
        let (text, hash) = compose(
            title: "  Boléro \t— Ravel\n(1928) ", artist: "Orchestre de Paris",
            album: "CLASSIQUE", genre: "Classical", duration: 149,
            playlists: ["Sommeil étoilé"], affinity: ["dormant"])
        XCTAssertEqual(text, "title: boléro — ravel (1928)\nartist: orchestre de paris\nalbum: classique\ngenre: classical\nduration: short\nplaylists: sommeil étoilé\naffinity: dormant")
        XCTAssertEqual(hash, "0625c8a31e5e8ebb5383522d572143ad42a09108f2cbf861e7ad84971bf2fadf")
    }

    func test_durationBoundaries_matchServerBuckets() {
        // Python: <=149 short, <=360 medium, else long; 150 is medium.
        let at150 = compose(title: "a", artist: "b", album: "c", genre: "d",
                            duration: 150, playlists: [], affinity: [])
        XCTAssertEqual(at150.hash, "6f5f18c68dae758f827235555bf7fbfb0249edd1f3074d3ffcdfed21ee81f452")
        XCTAssertTrue(at150.text.contains("duration: medium"))

        let at360 = compose(title: "a", artist: "b", album: "c", genre: "d",
                            duration: 360.0, playlists: [], affinity: [])
        XCTAssertEqual(at360.hash, "6f5f18c68dae758f827235555bf7fbfb0249edd1f3074d3ffcdfed21ee81f452")

        let over360 = compose(title: "a", artist: "b", album: "c", genre: "d",
                              duration: 360.5, playlists: [], affinity: [])
        XCTAssertEqual(over360.hash, "54416c42e359284a9aec5595a590665003e49ce19e77bc1466360dff30f0f717")
        XCTAssertTrue(over360.text.contains("duration: long"))

        // Fractional just under the short cutoff: 149.5 <= 149 is false in
        // both languages -> medium.
        XCTAssertEqual(LibraryDoc.durationBucket(149.5), "medium")
        XCTAssertEqual(LibraryDoc.durationBucket(149), "short")
    }

    func test_longFieldTruncation_matchesServer() {
        // 600 X's -> lowercased, truncated to 512; empty album stays empty and
        // empty genre falls back to "unknown".
        let (text, hash) = compose(
            title: String(repeating: "X", count: 600), artist: "y", album: "",
            genre: "", duration: 42, playlists: ["p1", "p2", "p3"],
            affinity: ["favorite", "frequent", "dormant"])
        let titleLine = text.split(separator: "\n").first.map(String.init) ?? ""
        XCTAssertEqual(titleLine, "title: " + String(repeating: "x", count: 512))
        XCTAssertEqual(hash, "b6c86e96add78b97016c361692c605683f31080853c8e50dc04d199d4199af18")
    }

    func test_cjkAndEmoji_matchServer() {
        let (text, hash) = compose(
            title: "夜に駆ける 🌙", artist: "YOASOBI", album: "THE BOOK",
            genre: "J-Pop", duration: 261.5, playlists: ["日本語 Mix"],
            affinity: ["frequent"])
        XCTAssertEqual(text, "title: 夜に駆ける 🌙\nartist: yoasobi\nalbum: the book\ngenre: j-pop\nduration: medium\nplaylists: 日本語 mix\naffinity: frequent")
        XCTAssertEqual(hash, "d9f67bf6e3190c25d929e2b10aea0e4192ea39f6f083b7b5445a9db417ba8b3a")
    }

    // MARK: - Helper behavior (mirrors _clean_text / _clean_list)

    func test_cleanList_dropsEmptiesAndCapsAt100() {
        let cleaned = LibraryDoc.cleanList(["  ", "One", "\t", "TWO  three"])
        XCTAssertEqual(cleaned, ["one", "two three"])

        let many = (0..<150).map { "P\($0)" }
        XCTAssertEqual(LibraryDoc.cleanList(many).count, 100)
    }

    func test_hash_isLowercaseSHA256Hex() {
        // sha256("abc") — universal known-answer test.
        XCTAssertEqual(
            LibraryDoc.hash("abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")
    }
}
