import CryptoKit
import Foundation

// MARK: - Document composition (mirrors backend/library_index.py byte-for-byte)

/// Client-side mirror of the server's document composition
/// (`compose_doc` / `_clean_text` / `_clean_list` / `_duration_bucket` /
/// `doc_hash` in `backend/library_index.py`).
///
/// The server recomposes the doc from the submitted fields and verifies the
/// client's `doc_hash`; a composition mismatch silently breaks delta sync
/// (every sync would re-index every track, or worse, skip changed ones). Any
/// change here MUST be mirrored in `library_index.py` and vice versa —
/// `LibraryDocCompositionTests` pins fixtures generated by running the real
/// Python composition.
///
/// Canonical doc shape (one line per field, all lowercase):
///
///     title: {title}
///     artist: {artist}
///     album: {album}
///     genre: {genre or "unknown"}
///     duration: {short|medium|long}     # <2:30 / 2:30-6:00 / >6:00
///     playlists: {names of playlists containing the track}
///     affinity: {flags}                 # favorite / recent / frequent / dormant
enum LibraryDoc {
    /// Mirrors `MAX_FIELD_LEN` (Python truncates by code point — we truncate
    /// by unicode scalar, which is the same unit).
    static let maxFieldLength = 512
    /// Mirrors `MAX_LIST_ITEMS`.
    static let maxListItems = 100

    /// Duration buckets in seconds — mirrors `_DURATION_SHORT_MAX = 150` /
    /// `_DURATION_MEDIUM_MAX = 360` with Python's exact comparisons:
    /// `seconds <= 149` → short, `seconds <= 360` → medium, else long,
    /// non-numeric (nil) → medium.
    static func durationBucket(_ seconds: Double?) -> String {
        guard let seconds else { return "medium" }
        if seconds <= 149 { return "short" }
        if seconds <= 360 { return "medium" }
        return "long"
    }

    /// Mirrors `_clean_text`: collapse runs of whitespace to a single space,
    /// trim, lowercase, truncate to 512 scalars, fall back to `defaultValue`
    /// when empty.
    static func cleanText(_ value: String?, defaultValue: String = "") -> String {
        guard let value else { return defaultValue }
        var cleaned = value.replacingOccurrences(
            of: "\\s+", with: " ", options: .regularExpression)
        cleaned = cleaned.trimmingCharacters(in: .whitespacesAndNewlines)
        cleaned = cleaned.lowercased()
        if cleaned.unicodeScalars.count > maxFieldLength {
            var scalars = String.UnicodeScalarView()
            scalars.append(contentsOf: cleaned.unicodeScalars.prefix(maxFieldLength))
            cleaned = String(scalars)
        }
        return cleaned.isEmpty ? defaultValue : cleaned
    }

    /// Mirrors `_clean_list`: first 100 items, each cleaned, empties dropped.
    static func cleanList(_ values: [String]) -> [String] {
        values.prefix(maxListItems).map { cleanText($0) }.filter { !$0.isEmpty }
    }

    /// Mirrors `compose_doc`.
    static func compose(
        title: String?,
        artist: String?,
        album: String?,
        genre: String?,
        durationSeconds: Double?,
        playlists: [String],
        affinity: [String]
    ) -> String {
        [
            "title: \(cleanText(title))",
            "artist: \(cleanText(artist))",
            "album: \(cleanText(album))",
            "genre: \(cleanText(genre, defaultValue: "unknown"))",
            "duration: \(durationBucket(durationSeconds))",
            "playlists: \(cleanList(playlists).joined(separator: " "))",
            "affinity: \(cleanList(affinity).joined(separator: " "))",
        ].joined(separator: "\n")
    }

    /// Mirrors `doc_hash`: SHA-256 hex (lowercase) of the UTF-8 doc text.
    static func hash(_ docText: String) -> String {
        SHA256.hash(data: Data(docText.utf8))
            .map { String(format: "%02x", $0) }
            .joined()
    }
}

// MARK: - Snapshot model

/// One track's fully composed sync document plus the raw fields the server
/// needs to recompose (and verify) it.
struct LibraryTrackDoc: Equatable {
    let trackID: String
    let title: String
    let artist: String
    let album: String?
    let genre: String?
    let duration: Double?
    let playlists: [String]
    let affinity: [String]
    let docText: String
    let docHash: String

    init(
        trackID: String,
        title: String,
        artist: String,
        album: String?,
        genre: String?,
        duration: Double?,
        playlists: [String],
        affinity: [String]
    ) {
        self.trackID = trackID
        self.title = title
        self.artist = artist
        self.album = album
        self.genre = genre
        self.duration = duration
        self.playlists = playlists
        self.affinity = affinity
        self.docText = LibraryDoc.compose(
            title: title, artist: artist, album: album, genre: genre,
            durationSeconds: duration, playlists: playlists, affinity: affinity)
        self.docHash = LibraryDoc.hash(docText)
    }
}

// MARK: - Sync service

/// Assembles the device's library snapshot (favorites + playlists + local
/// imports + recents), computes per-track `doc_hash` deltas against the
/// last-synced state, and POSTs them to `/api/library/sync`.
///
/// Persistence follows the standard store pattern: one `KeyValueStore` blob
/// (`library_sync_state.json`) holding the stable `device_id` and the
/// last-synced hash map, written through a 0.5 s `Debouncer` and flushed from
/// `ContentView.flushAllStores()` via `LibrarySearchManager`.
///
/// Trigger discipline (spec §5): library mutations and app-foreground call
/// `LibrarySearchManager`, which debounces 0.5 s and then consults the 60 s
/// min-interval gate (`shouldSync`) before invoking `sync()` here.
final class LibrarySyncService {
    /// Affinity vocabulary (must match the controlled vocabulary documented
    /// in `library_index.py` — BM25 and the embedder both index these terms):
    ///
    ///     favorite  — the track is currently favorited
    ///     recent    — played within the last 7 days
    ///     frequent  — in the top play-count quartile (and played >= 2 times)
    ///     dormant   — last played 60+ days ago ("stuff I haven't played in
    ///                 a while"); never-played tracks carry no flag because
    ///                 the client has no play record to bucket them with
    ///
    /// Flags use coarse time buckets so a track's doc hash doesn't churn on
    /// every play event — it changes only when a flag flips.
    static let recentWindow: TimeInterval = 7 * 86400
    static let dormantWindow: TimeInterval = 60 * 86400
    static let minIntervalBetweenSyncs: TimeInterval = 60

    struct State: Codable {
        var deviceID: String
        /// track_id → doc_hash at last successful sync.
        var syncedHashes: [String: String]
    }

    struct SyncDelta: Equatable {
        var changed: [LibraryTrackDoc]
        var deletedIDs: [String]
        var isEmpty: Bool { changed.isEmpty && deletedIDs.isEmpty }
    }

    struct SyncResponse: Decodable {
        let indexed: Int
        let skipped: Int
        let deleted: Int
    }

    enum SyncError: Error {
        case notConfigured
        case badURL
        case httpStatus(Int)
    }

    private let store: KeyValueStore
    private let session: URLSessionProtocol
    /// Resolved at call time — never freeze `BackendConfig` values in a
    /// `static let` (backend-config-seam rule). Returns `nil` when no
    /// backend is configured (local-only mode).
    private let resolveBaseURL: () -> String?
    private let resolveAPIKey: () -> String?
    private let now: () -> Date

    private var state: State
    private var saveDebouncer: Debouncer!
    /// Start time of the last *attempted* sync (success or failure) — the 60 s
    /// gate throttles attempts, not just successes, so a down backend isn't
    /// hammered.
    private(set) var lastSyncAttemptAt: Date?

    init(
        store: KeyValueStore = JSONFileStore(filename: "library_sync_state.json"),
        session: URLSessionProtocol = URLSessionAdapter(session: .shared),
        resolveBaseURL: @escaping () -> String? = {
            BackendConfig.isConfigured ? BackendConfig.baseURL : nil
        },
        resolveAPIKey: @escaping () -> String? = { BackendConfig.apiKey },
        now: @escaping () -> Date = Date.init
    ) {
        self.store = store
        self.session = session
        self.resolveBaseURL = resolveBaseURL
        self.resolveAPIKey = resolveAPIKey
        self.now = now
        self.state = SchemaStore.loadValue(State.self, from: store)
            ?? State(deviceID: UUID().uuidString, syncedHashes: [:])
        self.saveDebouncer = Debouncer(delay: 0.5) { [weak self] in self?.performSave() }
        // First launch: persist the freshly minted device_id immediately so it
        // stays stable across relaunches even if nothing ever syncs.
        if store.load() == nil { saveDebouncer.call() }
    }

    deinit { if saveDebouncer?.isPending == true { performSave() } }

    /// Stable per-install device identifier (UUID, matches the server's
    /// `^[A-Za-z0-9_-]{1,64}$` device_id shape).
    var deviceID: String { state.deviceID }

    var syncedHashes: [String: String] { state.syncedHashes }

    func flushPendingWrites() { saveDebouncer?.flush() }

    private func performSave() {
        guard let data = try? SchemaStore.encodeValue(state) else { return }
        try? store.save(data)
    }

    // MARK: Gate

    /// The 60 s min-interval gate fed by the 0.5 s mutation debouncer.
    static func shouldSync(
        now: Date, lastAttempt: Date?, minInterval: TimeInterval = minIntervalBetweenSyncs
    ) -> Bool {
        guard let lastAttempt else { return true }
        return now.timeIntervalSince(lastAttempt) >= minInterval
    }

    /// Seconds until the gate opens (0 when it is already open). Used to
    /// schedule the trailing retry so a gated mutation isn't lost.
    static func secondsUntilSyncAllowed(
        now: Date, lastAttempt: Date?, minInterval: TimeInterval = minIntervalBetweenSyncs
    ) -> TimeInterval {
        guard let lastAttempt else { return 0 }
        return max(0, minInterval - now.timeIntervalSince(lastAttempt))
    }

    // MARK: Snapshot assembly (pure, unit-tested)

    /// Builds the full library snapshot: the union of favorites, playlist
    /// tracks, local imports, and recently played, each with playlist
    /// membership and affinity flags composed into its search doc.
    static func buildSnapshot(
        favorites: [Track],
        playlists: [Playlist],
        localTracks: [LocalTrack],
        recentlyPlayed: [Track],
        playStats: [String: RecentlyPlayedManager.PlayStat],
        now: Date
    ) -> [LibraryTrackDoc] {
        // Universe: first occurrence wins for title/artist; nil album/duration
        // backfilled from later duplicates. Local imports go first (richest
        // metadata), then favorites, playlists, recents.
        struct Meta {
            var title: String
            var artist: String
            var album: String?
            var duration: Double?
        }
        var order: [String] = []
        var meta: [String: Meta] = [:]

        func add(id: String, title: String, artist: String, album: String?, duration: Double?) {
            if var existing = meta[id] {
                if existing.album == nil { existing.album = album }
                if existing.duration == nil { existing.duration = duration }
                meta[id] = existing
            } else {
                order.append(id)
                meta[id] = Meta(title: title, artist: artist, album: album, duration: duration)
            }
        }

        for local in localTracks where !local.isMissing {
            add(
                id: "local:\(local.id.uuidString)",
                title: local.title,
                artist: local.artist ?? "This Device",
                album: local.album,
                duration: local.durationSeconds)
        }
        for track in favorites where !track.isMissing {
            add(id: track.id, title: track.title, artist: track.artist,
                album: track.album, duration: track.duration)
        }
        for playlist in playlists {
            for track in playlist.tracks where !track.isMissing {
                add(id: track.id, title: track.title, artist: track.artist,
                    album: track.album, duration: track.duration)
            }
        }
        for track in recentlyPlayed where !track.isMissing {
            add(id: track.id, title: track.title, artist: track.artist,
                album: track.album, duration: track.duration)
        }

        // Playlist membership, sorted by cleaned name so reordering playlists
        // in the UI never churns doc hashes.
        var membership: [String: [String]] = [:]
        for playlist in playlists {
            for track in playlist.tracks {
                membership[track.id, default: []].append(playlist.name)
            }
        }
        for (id, names) in membership {
            membership[id] = names.sorted { LibraryDoc.cleanText($0) < LibraryDoc.cleanText($1) }
        }

        let favoriteIDs = Set(favorites.map(\.id))
        let frequentThreshold = Self.frequentThreshold(playStats: playStats)

        return order.map { id in
            let m = meta[id]!
            var affinity: [String] = []
            if favoriteIDs.contains(id) { affinity.append("favorite") }
            if let stat = playStats[id] {
                let age = now.timeIntervalSince(stat.lastPlayedAt)
                if age < recentWindow { affinity.append("recent") }
                if let threshold = frequentThreshold, stat.playCount >= threshold {
                    affinity.append("frequent")
                }
                if age >= dormantWindow { affinity.append("dormant") }
            }
            return LibraryTrackDoc(
                trackID: id,
                title: m.title,
                artist: m.artist,
                album: m.album,
                genre: nil, // no genre metadata in the app's models today
                duration: m.duration,
                playlists: membership[id] ?? [],
                affinity: affinity)
        }
    }

    /// "frequent" = top play-count quartile: the 75th-percentile play count
    /// (nearest-rank over all played tracks), never below 2 so single plays
    /// can't qualify. Returns nil when nothing has been played.
    static func frequentThreshold(playStats: [String: RecentlyPlayedManager.PlayStat]) -> Int? {
        let counts = playStats.values.map(\.playCount).filter { $0 > 0 }.sorted()
        guard !counts.isEmpty else { return nil }
        let idx = (3 * (counts.count - 1)) / 4
        return max(2, counts[idx])
    }

    // MARK: Delta

    /// Changed = new or hash-differing tracks; deleted = ids the server has
    /// (per the last-synced map) that left the library.
    static func computeDelta(
        current: [LibraryTrackDoc], lastSynced: [String: String]
    ) -> SyncDelta {
        let changed = current.filter { lastSynced[$0.trackID] != $0.docHash }
        let currentIDs = Set(current.map(\.trackID))
        let deleted = lastSynced.keys.filter { !currentIDs.contains($0) }.sorted()
        return SyncDelta(changed: changed, deletedIDs: deleted)
    }

    // MARK: Network

    private struct TrackPayload: Encodable {
        let track_id: String
        let doc_hash: String
        let title: String
        let artist: String
        let album: String?
        let genre: String?
        let duration: Double?
        let playlists: [String]
        let affinity: [String]
    }

    private struct SyncPayload: Encodable {
        let device_id: String
        let tracks: [TrackPayload]
        let deleted_track_ids: [String]
    }

    /// POSTs the delta for `snapshot`; on success records the full current
    /// hash map (debounced write). Skips the network entirely when nothing
    /// changed. Marks the attempt time up front so the 60 s gate throttles
    /// failures too.
    func sync(snapshot: [LibraryTrackDoc]) async throws {
        lastSyncAttemptAt = now()
        guard let base = resolveBaseURL() else { throw SyncError.notConfigured }

        let delta = Self.computeDelta(current: snapshot, lastSynced: state.syncedHashes)
        if delta.isEmpty { return }

        guard let url = URL(string: "\(base)/api/library/sync") else { throw SyncError.badURL }
        let payload = SyncPayload(
            device_id: state.deviceID,
            tracks: delta.changed.map {
                TrackPayload(
                    track_id: $0.trackID, doc_hash: $0.docHash, title: $0.title,
                    artist: $0.artist, album: $0.album, genre: $0.genre,
                    duration: $0.duration, playlists: $0.playlists, affinity: $0.affinity)
            },
            deleted_track_ids: delta.deletedIDs)
        let body = try JSONEncoder().encode(payload)

        let (_, response) = try await session.data(
            for: .backendPOST(url, jsonBody: body, apiKey: resolveAPIKey()))
        if let http = response as? HTTPURLResponse, http.statusCode >= 400 {
            throw SyncError.httpStatus(http.statusCode)
        }

        state.syncedHashes = Dictionary(
            uniqueKeysWithValues: snapshot.map { ($0.trackID, $0.docHash) })
        saveDebouncer.call()
    }

    /// Privacy delete (spec §10 step 6): best-effort `DELETE /api/library` at
    /// an explicit (usually *old*) base URL when the user clears or changes
    /// the backend, then forget all synced-hash state so a future backend
    /// starts fresh. The device_id is kept — it's a random UUID, and reusing
    /// it lets the same server pair cleanly if re-added.
    func deleteRemoteAndReset(oldBaseURL: String?) async {
        let hadState = !state.syncedHashes.isEmpty
        state.syncedHashes = [:]
        if hadState { saveDebouncer.call() }
        lastSyncAttemptAt = nil

        guard let oldBaseURL,
              var components = URLComponents(string: "\(oldBaseURL)/api/library")
        else { return }
        components.queryItems = [URLQueryItem(name: "device_id", value: state.deviceID)]
        guard let url = components.url else { return }
        // Best-effort: never block or surface errors — the old server may
        // already be unreachable, and local state is cleared regardless.
        _ = try? await session.data(for: .backendDELETE(url, apiKey: resolveAPIKey()))
    }
}
